[package]
name = "analyzer"
version.workspace = true
edition.workspace = true

[dependencies]
ast.workspace = true
lint = { version = "0.0.7", path = "../lint" }
query.workspace = true
symbol_table = { path = "../symbol_table" }
thiserror = "2.0.17"
