[package]
name = "analyzer"
version.workspace = true
edition.workspace = true

[dependencies]
ast.workspace = true
lint.workspace = true
query.workspace = true
symbol_table.workspace = true
thiserror = "2.0.17"
