[package]
name = "simplifier"
version.workspace = true
edition.workspace = true

[dependencies]
ast.workspace = true
parser.workspace = true
symbol_table = { version = "0.1.0", path = "../symbol_table" }
