[package]
name = "monomorphize"
version.workspace = true
edition.workspace = true

[dependencies]
ast.workspace = true
const_eval = { path = "../const_eval" }
query.workspace = true
symbol_table = { path = "../symbol_table" }
