[package]
name = "monomorphize"
version.workspace = true
edition.workspace = true

[dependencies]
ast.workspace = true
const_eval = { version = "0.1.0", path = "../const_eval" }
query.workspace = true
