[package]
name = "monomorphize"
version.workspace = true
edition.workspace = true

[dependencies]
ast.workspace = true
const_eval.workspace = true
query.workspace = true
symbol_table.workspace = true
