[package]
name = "parser"
version.workspace = true
edition.workspace = true

[dependencies]
peg = "0.8.5"
ast.workspace = true
anyhow.workspace = true
logos = "0.16.0"
line-column = "0.3.1"
unescaper = "0.1.8"
lint.workspace = true

[features]
trace = ["peg/trace"]
